const express = require('express')
const deb = require('./config/mongoose-connection')
const cookieParser = require('cookie-parser')
const jwt = require('jsonwebtoken')
const bcrypt = require('bcrypt')
const path = require('path')
const app = express()
const owenersRouter = require('./routes/owenersRouter')
const productsRouter = require('./routes/productsRouter')
const usersRouter = require('./routes/usersRouter')


app.set('view engine','ejs')
app.use(express.json())
app.use(cookieParser())
app.use(express.urlencoded({extended:true}))
app.use(express.static(path.join(__dirname, 'public')))
app.use('/oweners',owenersRouter)
app.use('/users',usersRouter)
app.use('/products',productsRouter)

app.listen(3000)